[package]
name = "reverust"
version = "0.1.0"
authors = ["ktetsuo <ktetsuo@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.7"
glam = { version = "0.20", features = ["mint"]}
